image:
  name: hashicorp/terraform:1.7.5
  entrypoint: ["/bin/sh", "-c"]

variables:
    AWS_ACCESS_KEY_ID: ${MY_AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${MY_AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: "us-east-1"

before_script:
    - terraform --version
    - terraform init

stages:
    - validate
    - plan_and_apply
    - destroy

validate:
    stage: validate
    script:
        - terraform validate

plan_and_apply:
    stage: plan_and_apply
    dependencies:
        - validate
    script:
        - terraform plan
        - terraform apply -auto-approve
    when: manual

destroy:
    stage: destroy
    dependencies:
        - plan_and_apply
    script:
        - terraform destroy -auto-approve
    when: manual
